### ISSUE TITLE
[gateway] [management] support Kerberos (SPNEGO)

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#3555]
- [x] Read about Kerberos & SPNEGO
- [x] Create Test Env
- [x] Implement AM IdP to connect Kerberos principal using Login/Pwd
- [x] Implement AM IdP to connect Kerberos principal using SPNEGO

**Comment by leleueri** [comment]
Test environment available here : https://github.com/leleueri/docker-kerberos
