### ISSUE TITLE
[management] cockpit integration

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#4597]

**Comment by leleueri** [comment]
- [ ] #4947 - cockpit url configurable
- [ ] #4942 - handle installation event
- [ ] #4765 - manage cockpit installation 
- [ ] #4528 - link user to the right organization through social IdP
- [ ] #4529 - script permission 
- [ ] rebase onto master

**Comment by jhaeyaert** [comment]
I suggest to address #4958 after the rebase has been performed.
