### ISSUE TITLE
Use the bridgeCommand to list available environments

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5607]
## Description

The goal of this issue is to implement all the technical stuff needed on APIM side to send, process and reply to a `BridgeCommand`. The first use of this will be to list all the environments available when a user wants to promote an API.

## Tasks

  - [x] Create a `CommandService` that encapsulate `WebSocketCockpitConnector` and expose a synchronous `sendCommand` method
  - [x] Create a `BridgeCommandFactory.createListEnvironmentCommand()` (the goal is just to instantiate a `BridgeCommand`, the latter isn't meant to be inherited)
  - [x] Create a `BridgeCommandHandler` that will handle all `BridgeCommand`, parse them and delegate the management to a specific handler according to the command's ` operation` attribute
  - [x] Create `ListEnvironmentBridgeCommandHandler` that call the environment service and send a reply (`BridgeMultiReply`)
  - [x] Create a new `ApiPromotionResource`? And add a `/api-promotion/environments` endpoint?
  - [x] Handle unknown `operation`
