### ISSUE TITLE
Migrate APIM from a multi-repo to a mono-repo project.

### ISSUE THREAD

**Issue by phiz71** [gravitee-io/issues#5669]
### Introduction
The purpose of this issue is to consider this migration of APIM to simplify its development and its release process.
With multiple repositories, dependancies between repositories had to be managed manually (vs. using maven) which makes the release process more complicated.
It is also very hard for commiters to open PRs, since they have to clone multiple repos.

### Goal and requirements
The final goal is to have one GitHub repository to gather all APIM repositories:
- [x]  gravitee-gateway (APIM Gateway)
- [x]  gravitee-managment-rest-api (APIM APIs)
- [x]  gravitee-management-webui (APIM Console)
- [x]  gravitee-portal-webui (APIM Portal)
- [x]  gravitee-repository (with -test, -mongodb, -jdbc, -gateway-bridge-http, -redis, -hazelcast)
- [x]  gravitee-reporter (with -api, -conf, -file, -kafka, -tcp)
- [x]  gravitee-elasticsearch
- [x]  gravitee-definition

The migration has to be done for all "support + master branches" of all repositories and we should keep the commit history. However, it seems  hard to keep tags, since all current repositories have their own version number.

### How to ?
As a first step (and POC), we should create a new GitHub repository and import all `gravitee-repository-XXX` repositories.
The release process of theses repositories should obviously be modified.

Once this first step done, we could then repeat the process for others GH repositories.

**Comment by gaetanmaisse** [comment]
Closing as it has been done
