### ISSUE TITLE
Init APIM monorepo with `gravitee-repository-*`

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#5821]
## Bootstrap APIM Monorepo

 - [x] Create GitHub repository -> 
 - [x] Use [repo combiner](https://github.com/gaetanmaisse/gravitee-repo-combiner) to init monorepo with: 
      - repositories: ``
      - branches: `master`, `3.9.x`, `3.8.x`, `3.5.x` and `3.0.x`
  - [x] Init pom.xml and rename artifacts
  - [x] Add CircleCI config

Repository: https://github.com/gravitee-io/gravitee-api-management
CircleCI builds: https://app.circleci.com/pipelines/github/gravitee-io/gravitee-api-management
Nexus artefacts: https://oss.sonatype.org/#nexus-search;gav~io.gravitee.apim.repository~gravitee-apim-repository-api~~~~kw,versionexpand

## Update artefacts in `gravitee-gateway` repo

 - [x] `master` https://github.com/gravitee-io/gravitee-gateway/pull/697
 - [x] `3.9.x` https://github.com/gravitee-io/gravitee-gateway/pull/698
 - [x] `3.8.x` https://github.com/gravitee-io/gravitee-gateway/pull/699
 - [x] `3.5.x` https://github.com/gravitee-io/gravitee-gateway/pull/700
 - [x] `3.0.x` https://github.com/gravitee-io/gravitee-gateway/pull/701

## Update artefacts in `gravitee-management-rest-api` repo

 - [x] `master` https://github.com/gravitee-io/gravitee-management-rest-api/pull/1553
 - [x] `3.9.x` https://github.com/gravitee-io/gravitee-management-rest-api/pull/1554
 - [x] `3.8.x` https://github.com/gravitee-io/gravitee-management-rest-api/pull/1556
 - [x] `3.5.x` https://github.com/gravitee-io/gravitee-management-rest-api/pull/1557
 - [x] `3.0.x` https://github.com/gravitee-io/gravitee-management-rest-api/pull/1558

## Update `release.json` in `release` repo

 - [x] `master` https://github.com/gravitee-io/release/pull/281
 - [x] `3.9.x` https://github.com/gravitee-io/release/pull/282
 - [x] `3.8.x` https://github.com/gravitee-io/release/pull/283
 - [x] `3.5.x` https://github.com/gravitee-io/release/pull/284
 - [x] `3.0.x` https://github.com/gravitee-io/release/pull/285

## Update packaging script in `jenkins-scripts` repo

 - [x] https://github.com/gravitee-io/jenkins-scripts/pull/44

## TODO
 - [x] Add README in `gravitee-api-management` https://github.com/gravitee-io/gravitee-api-management/pull/5
 - [x] Update pom parent to 20.0 in `gravitee-api-management` https://github.com/gravitee-io/gravitee-api-management/pull/6
 - [x] Clean dependency management in `gravitee-api-management` https://github.com/gravitee-io/gravitee-api-management/pull/6
 - [x] Open source `gravitee-api-management`
 - [x] Archive (read-only mode) `gravitee-repository-*` GitHub repositories + update README (disclaimer + link to`gravitee-api-management`) ⚠️  WAIT FOR 3.5.17 release:
   - https://github.com/gravitee-io/gravitee-repository/pull/216
   - https://github.com/gravitee-io/gravitee-repository-gateway-bridge-http/pull/52
   - https://github.com/gravitee-io/gravitee-repository-hazelcast/pull/3
   - https://github.com/gravitee-io/gravitee-repository-jdbc/pull/182
   - https://github.com/gravitee-io/gravitee-repository-mongodb/pull/220
   - https://github.com/gravitee-io/gravitee-repository-redis/pull/106
   - https://github.com/gravitee-io/gravitee-repository-test/pull/192
 - Add information in release README about the naming breaking change:
    - [ ] `master` https://github.com/gravitee-io/release/pull/286
    - [ ] `3.9.x` https://github.com/gravitee-io/release/pull/290
    - [ ] `3.8.x` https://github.com/gravitee-io/release/pull/289
    - [ ] `3.5.x` https://github.com/gravitee-io/release/pull/288
    - [ ] `3.0.x` https://github.com/gravitee-io/release/pull/287
 - [ ] Update docs.gravitee.io https://github.com/gravitee-io/gravitee-docs/pull/449
