### ISSUE TITLE
[fapi] Brazil Open Banking implementation

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#5994]
- [x] Dynamic Scope validation : https://bitbucket.org/openid/fapi/src/master/Financial_API_Lodging_Intent.md
- [x] RequestObject using JWE+JWS required (or use PAR ==> mean that encryption isn't required using PAR???) : decode RequestObject using server private key
- [x] DCR Client registration control of client metadata conformance (https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-dynamic-client-registration-1_ID1.html#section-7)
- [x] Support of acr_values LoA2&3 : https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID2.html#section-5.2.2.4
- [x] Support of claims cpf/cnpj : https://openbanking-brasil.github.io/specs-seguranca/open-banking-brasil-financial-api-1_ID2.html#section-5.2.2.3
- [x] shall advertise mtls_endpoint_aliases as per clause 5 RFC 8705 OAuth 2.0 Mutual-TLS Client Authentication and Certificate-Bound Access Tokens the token_endpoint, registration_endpoint and userinfo_endpoint; AND if supporting OAuth 2.0 Pushed Authorization Requests shall advertise through OIDD mtls_endpoint_aliases the pushed_authorization_request_endpoint;

**Comment by tcompiegne** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Graviteeio---Access-Management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/5994?planning-poker) with ZenHub @leleueri @DCourtneyGravitee @remisultan
