### ISSUE TITLE
Setup SonarCloud to get test coverage information on WebUI

### ISSUE THREAD

**Issue by gaetanmaisse** [gravitee-io/issues#6053]
**Description**

Currently, SonarCloud is doing a simple automatic analysis on each PR open in WebUI repo and then add a comment with the analysis result. A missing piece of information is the code coverage, to have it we will need to do some setup and trigger a manual analysis.

**Todo**

- [ ] Create a `sonar-project.properties` file at the root of the repo with something like:
```
sonar.organization=gravitee-io
sonar.projectKey=gravitee-io_gravitee-management-webui

# Path to sources
sonar.sources=src

# Source encoding
sonar.sourceEncoding=UTF-8

# Coverage
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.test=src
sonar.test.inclusions=**/*.test.ts*
```
 - [ ] Update `Jest` config to output a `lcov` file
 - [ ] Update CircleCI config to run Sonarscanner manually as `Code coverage` isn't supported by automatic analysis, see https://sonarcloud.io/documentation/advanced-setup/automatic-analysis/#prerequisites. There is an [orb](https://circleci.com/developer/orbs/orb/sonarsource/sonarcloud) to simplify the integration, but be careful maybe not everything is available with it, for instance are we able to set the version linked to the analysis?
