### ISSUE TITLE
[management] [CICD] Creation of service account

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#6467]
As an admin, I want to create a service account to use for CICD purpose.

### Expected Behavior

- create a user without a required email (no password then)
- if a service account is created with email, he can set a password / reset it

<img width="1848" alt="Capture d’écran 2021-10-28 à 12 02 41" src="https://user-images.githubusercontent.com/3227037/139236265-c040507e-07c9-4bad-8697-50f1e9a75888.png">
<img width="1857" alt="Capture d’écran 2021-10-28 à 12 06 08" src="https://user-images.githubusercontent.com/3227037/139236277-5671b433-994c-4489-8920-e369629e4580.png">

### Testing

- [x] Given an administrator, when I navigate to organizations settings > users, then I can click on "Register a service user"
- [x] Given an administrator, when I navigate to organizations settings > user an I click on "Register a service user", then a new form appears
- [x] Given an administrator, when registering a service user, I can fill a name, an email and create the user.
- [x] Given an administrator, when registering a service user, I can fill a name and create the user.
- [x] Given an administrator, when i've registered a service user, I can add it to a group.
- [x] Given an administrator, when i've registered a service user, I can add it to an API as a member.
- [x] Given an administrator, when i've registered a service user, I can view it in the users list.
- [x] Given an administrator, when i've registered a service user, I can add it to a group.
- [x] Given an administrator, when i've registered a service user, I can set him role of `API_Publisher` on `Default Environment`

### Tasks

- [x] Documentation

**Comment by LiliaEn** [comment]
Tested on the default environment version 3.14.0
Browser: Chrome Version 94.0.4606.81, macOS Big Sur v11.6
Covered the testing scenarios listed in the ticket description, the ones below + exploratory testing:

- [ ] Add a group to the user from User details page
- [ ] Add the user to a group from Settings-Groups
- [ ] Assign other roles
- [ ] Remove roles
- [ ] Delete user
- [ ] Add the user to an API,App
- [ ] Remove a user from an API, APP
- [ ] Add a service user as a member to an App from Portal
- [ ] Transfer ownership of an API to a service user

The following issues were reported: #6608 , #6602
