### ISSUE TITLE
[gateway] Performances improvements

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/issues#6492]
Steps: 

- [x] Remove Spring context at API level (review)
- [x] Rework Classloader management (https://github.com/gravitee-io/issues/issues/6758)
- [x] Migrate redis to connector to vertx (https://github.com/gravitee-io/issues/issues/6429)
- [x] Rework HTTP headers  (https://github.com/gravitee-io/issues/issues/6772)
