### ISSUE TITLE
3.15 LTS: Regression Testing

### ISSUE THREAD

**Issue by patelami** [gravitee-io/issues#6720]
List of all the high priority / high severity testing checklist for 3.15 LTS release : 

# General tests

- [x] Test database with version upgrade 
- [x] Test fresh database
- [x] Run all the postman tests on 3.15 nightly build
- [x] Stress tests
- [x] Test connection with Cockpit
- [x] Test connection with Alert Engine
- [x] Test sending an email => KO : https://github.com/gravitee-io/issues/issues/6928, wait 3.14.4 merge

# Previous regression issues

- [x] https://github.com/gravitee-io/issues/issues/6672: we should be able to create an organization user
- [x] https://github.com/gravitee-io/issues/issues/6382: on Register & ForgotPassword, when a PasswordPolicy isn't configured, the submit button should be activated, when a password policy is created it should disable until the password match the rules.
- [x] https://github.com/gravitee-io/issues/issues/5866: when a brute force is enabled, trying to connect an unknown user shouldn't create it if a brute force is detected.
- [x] https://github.com/gravitee-io/issues/issues/5306 : try to sign in a domain user with the username or the emailAddress
- [x] If two users with different username have the same email address, we should ensure that we request an additional information to specify the username. (need specific configuration)
- [x] we should customize a form and email template to validate that there are no issue during non default template processing
- [x] we should create organization users with different roles to validate that rights are managed properly (ORGANIZATION_OWNER or ORG_PRIMARY_OWNER have full access, ORGANIZATION_USER need permissions on DOMAIN or APPLICATION)

# Use Cases

1. Sign-in (username/password) flow

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Connect a user using the flow defined by the application

2. Social sign-in flow

- [x] Create domain
- [x] Create application
- [x] Set-up social IdP
- [x] Connect a user using the social IdP

3. Passwordless sign-in flow

- [x] Create domain
- [x] Create application
- [x] Set-up WebAuthn
- [x] Connect a user using WebAuthn

4. Sign-in (username/password) + MFA flow

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Set up one MFA factor
- [x] Connect a user with MFA (both Enroll and Challenge step)

5. Social sign-in + MFA flow

- [x] Create domain
- [x] Create application
- [x] Set-up social IdP
- [x] Set up one MFA factor
- [x] Connect a user using the social IdP => should display the MFA Enroll and Challenge pages

6. Passwordless sign-in + MFA flow

- [x] Create domain
- [x] Create application
- [x] Set-up WebAuthn
- [x] Set up one MFA factor
- [x] Connect a user using WebAuthn => should display the MFA Enroll and Challenge pages

7. Sign-in (username/password) with advanced enrich profile flow

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Create POST-LOGIN flow with both http callout and enrich profile policies
- [x] Connect a user using the flow defined by the application
- [x] Create custom token with enriched profile information

**Comment by leleueri** [comment]
Hi,

Here is some issues on which we had regression in the past. It maybe useful to perform some tests on them.

* https://github.com/gravitee-io/issues/issues/6672: we should be able to create an organization user
* https://github.com/gravitee-io/issues/issues/6382: on Register & ForgotPassword, when a PasswordPolicy isn't configured, the submit button should be activated, when a password policy is created it should disable until the password match the rules.
* https://github.com/gravitee-io/issues/issues/5866: when a brute force is enabled, trying to connect an unknown user shouldn't create it if a brute force is detected.

In addition here is some others use cases to test:

* https://github.com/gravitee-io/issues/issues/5306 : try to sign in a domain user with the username or the emailAddress
* If two users with different username have the same email address, we should ensure that we request an additional information to specify the username. (need specific configuration)
* we should customize a form and email template to validate that there are no issue during non default template processing
* we should create organization users with different roles to validate that rights are managed properly

**Comment by tcompiegne** [comment]
[ ] - Test connection with Cockpit
[ ] - Test connection with Alert Engine
