### ISSUE TITLE
QA regression checklist for 3.14

### ISSUE THREAD

**Issue by RubenMMSantos** [gravitee-io/issues#6753]
This ticket is to function as a place holder so we can keep track of the current state of regression on APIM 3.14.

Once ticket is completed, then the 3.14 release can start.

For 3.14 the plan is to:

- [x] have 3.13 merged into release environment
- [x] have all tickets for 3.14 tested and in "ready to release" column
- [x] have any issues raised during testing fixed, re-tested and moved to "ready to release" column
- [x] code freeze on release environment (no more tickets merged)
- [x] execute the regression test pack
- [x] execute the risk based test Coverage for specific work done for 3.14 release
