### ISSUE TITLE
[management] certificates expiration notification

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#6833]
## :rainbow: Feature

**As a** 'an security domain admin'

**I want to** 'be notified when a certificate will expire'

**So that** 'I can update those certificates to avoid potential downtime.'

## :sunrise_over_mountains: Additional information

- Create a watcher "soon expired certificates" service. 
- This watcher service will call "notification service" to trigger the notifications
- A new email template should be created
- We should be able to configure the deadline to trigger the notification
- We should be able to configure how often the notification will be triggered
- The console UI must displayed a warning if a certificate will expired
- For a v1 we have to decide which admin users will be notified ???

## :books: Documentation required

Provide link to the issue for documentation update

TODO

## :superhero: Acceptance criteria

- [ ] Given 'the security domain certificates'
- [ ] When 'a certificate will soon expire'
- [ ] Then 'a warning message will be displayed on the portal and an admin will be notified'

## :warning: Potential impacts

***What are the impacted versions?***

3.16

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:

**Comment by patelami** [comment]
Env: nightly
Result: PASS

Given I have create a certificate in Console 
And  the certificate is expired
Then I should see this information on expiration when I go to **certificates**
And I should receive the notification about the certificate expiry  
PASS

Given I have create a certificate in Console 
And  the certificate is expiring in 5 days
Then I should see this information on expiration when I go to **certificates**
PASS
And I should receive the notification about the certificate expiry  
<img width="1370" alt="Screenshot 2022-03-15 at 15 31 00" src="https://user-images.githubusercontent.com/14215437/158424267-abb515e2-649a-4c21-b3b8-1276ec978b0c.png">
<img width="1396" alt="Screenshot 2022-03-15 at 17 23 17" src="https://user-images.githubusercontent.com/14215437/158435771-5f32c84b-dbf4-480d-961a-dc3e6ffb4688.png">
