### ISSUE TITLE
3.17.0 UAT / regression tests

### ISSUE THREAD

**Issue by leleueri** [gravitee-io/issues#7296]
List of all the high priority / high severity testing checklist for 3.17 release : 

# General tests

- [x] Test database with version upgrade (:warning: beware to identity provider enabled on your app, after migration the IDP must be enabled)
- [x] Test fresh database
- [x] Run all the postman tests on 3.17 nightly build
- [x] Run all Postman tests on all supported RDBMS (Postgres, MariaDB, SQLServer, MySQL)
- [x] Test connection with Cockpit
- [x] Test connection with Alert Engine (connector 1.6.1 and AE in version 1.5.x & 1.6.x)
- [x] Test custom both form and email template
- [x] Test organization users with different roles to validate that rights are managed properly 
- Stress tests => STILL NOT READY

# Previous regression issues

- [x] https://github.com/gravitee-io/issues/issues/7118, sub value should match user technical ID
- [x] https://github.com/gravitee-io/issues/issues/7056, empty plugin configuration should work
- [x] https://github.com/gravitee-io/issues/issues/7080, AM API should not block with JDBC
- [x] https://github.com/gravitee-io/issues/issues/7035, MongoDB and JDBC users should be flagged as "internal"
- [x] https://github.com/gravitee-io/issues/issues/6928, we should be able to send an email
- [x] https://github.com/gravitee-io/issues/issues/6672: we should be able to create an organization user
- [x] https://github.com/gravitee-io/issues/issues/6382: on Register & ForgotPassword, when a PasswordPolicy isn't configured, the submit button should be activated, when a password policy is created it should disable until the password match the rules.
- [x] https://github.com/gravitee-io/issues/issues/5866: when a brute force is enabled, trying to connect an unknown user shouldn't create it if a brute force is detected.
- [x] https://github.com/gravitee-io/issues/issues/5306 : try to sign in a domain user with the username or the emailAddress
- [x] If two users with different username have the same email address, we should ensure that we request an additional information to specify the username. (need specific configuration)

# Use Cases

1. Sign-in (username/password) flow => Cover by postman end-to-end test

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Connect a user using the flow defined by the application

2. Social sign-in flow

- [x] Create domain
- [x] Create application
- [x] Set-up social IdP
- [x] Connect a user using the social IdP

3. Passwordless sign-in flow

- [x] Create domain
- [x] Create application
- [x] Set-up WebAuthn
- [x] Connect a user using WebAuthn

4. Sign-in (username/password) + MFA flow => Cover by postman end-to-end test

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Set up one MFA factor
- [x] Connect a user with MFA (both Enroll and Challenge step)

5. Social sign-in + MFA flow

- [x] Create domain
- [x] Create application
- [x] Set-up social IdP
- [x] Set up one MFA factor
- [x] Connect a user using the social IdP => should display the MFA Enroll and Challenge pages

6. Passwordless sign-in + MFA flow

- [x] Create domain
- [x] Create application
- [x] Set-up WebAuthn
- [x] Set up one MFA factor
- [x] Connect a user using WebAuthn => should display the MFA Enroll and Challenge pages

7. Sign-in (username/password) with advanced enrich profile flow

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Create POST-LOGIN flow with both http callout and enrich profile policies
- [x] Connect a user using the flow defined by the application
- [x] Create custom token with enriched profile information

**Comment by LalithaGu** [comment]
Tested the Use case 1 and 2. 
For Use case 2, I have tested "Social sign-in flow" by setting up the Social IDP- Google.
