### ISSUE TITLE
[Spike investigation] M-API Partial update

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#7417]
## :rainbow: Feature

Implementing a crossId on resources, fixing some behavior on import/export APIs is a great start on our path to provide easy integration of Gravitee in a CICD workflow.
To follow up on these improvements, we’d like to let the user update their APIs without bringing the full API Definition. The idea is to implement a PATCH method.

Which endpoint should we target? Imho we should focus on these two :
PUT /api/import
PUT /api/{api.id}/import

In order to keep consistency and provide guidance easily (and avoid custom implementation around M-API).

Should we be able to update all info or not?

## :sunrise_over_mountains: Additional information

- PATCH on the API resource and not the import
- Should we be able to update all info or not? 
- A lot of tests to plan

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

Insert screenshots, drawings...

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

## :heavy_check_mark: Definition of Done

***For each User Story everything on the list must be considered, select only what was required***
- [ ] Acceptance criteria met and tested
- [ ] Sonar Cloud quality gate passes
- [ ] CircleCi checks pass
- [ ] Cypress or Postman API check passes
- [ ] Test containers passed if modifications on the repository modules
- [ ] Translation for portal UI checked
- [ ] Developer created draft documentation PR
- [ ] New migration scripts checked
Can be run multiple times but only makes changes the first time
Display to user what script has done
- [ ] Validated on appropriate environment
- [ ] Existing test cases refactored

:rocket:
