### ISSUE TITLE
3.18.0 UAT / regression tests

### ISSUE THREAD

**Issue by omatthewsgravitee** [gravitee-io/issues#7820]
List of all the high priority / high severity testing checklist for [3.18 release](https://github.com/gravitee-io/issues/milestone/502) : 

# General tests

- [x] Test database with version upgrade from 3.15.0 (last LTS) (:warning: beware to identity provider enabled on your app, after migration the IDP must be enabled)
- [x] Test fresh database
- [x] Run all the postman tests on 3.18 nightly build
- [x] Run all Postman tests on all supported RDBMS (MySQL)
- [x] Run all Postman tests on all supported RDBMS (SQLServer)
- [x] Run all Postman tests on all supported RDBMS (MariaDB)
- [x] Run all Postman tests on all supported RDBMS (Postgres)
- [x] Test connection with Cockpit
- [x] Test connection with Alert Engine (just use a license.key, AE connector is provoded by default into the new bundle)
- [x] Test custom both form and email template
- [x] Test certificate expiration notification
- [ ] Test organization users with different roles to validate that rights are managed properly 
- Stress tests => STILL NOT READY

# New Feature Highligth

## MFA FIDO2

For the MFA FIDO2, please test the scenarios described here https://miro.com/app/board/uXjVO5tlcv0=/

Please, test also all the MFA flow chart options using FIDO2 as factor:

- [x] when user doesn't use webauthn as authentication mechanism
- [x] when user uses webauthn as authentication mechanism

Also, please test passwordless with : 

- [x] MacOS 
- [x] Yubikey
- [x] Android (using the pattern - test wrong pattern and then good pattern)
- [x] Android with Yubikey
- [ ] iOS 

## Intelligent Adaptative Access (EPIC [7552](https://github.com/gravitee-io/issues/issues/7552))

// TODO

## ECDSA token signature

- [x] create domain with ECDSA default sign algorithm
- [x] upload EC certificate on domain and use it with an app
- [x] upload RSA certificate on domain and use it with an app

# Issue coming from maintenance release that need to be tester after merge

- [x] https://github.com/gravitee-io/issues/issues/7708
- [ ] Same as 7708 but  with "hide form" disable and a selection rule active to see behaviour
- [x] https://github.com/gravitee-io/issues/issues/7679
- [x] https://github.com/gravitee-io/issues/issues/7616
- [x] https://github.com/gravitee-io/issues/issues/7619
- [x] https://github.com/gravitee-io/issues/issues/7759
- [x] https://github.com/gravitee-io/issues/issues/7753
- [x] https://github.com/gravitee-io/issues/issues/7470
- [x] https://github.com/gravitee-io/issues/issues/7471
- [ ] https://github.com/gravitee-io/issues/issues/7797
- [x] https://github.com/gravitee-io/issues/issues/7678

# Previous regression issues

- [x] https://github.com/gravitee-io/issues/issues/7118, sub value should match user technical ID
- [x] https://github.com/gravitee-io/issues/issues/7056, empty plugin configuration should work
- [x] https://github.com/gravitee-io/issues/issues/7080, AM API should not block with JDBC
- [x] https://github.com/gravitee-io/issues/issues/7035, MongoDB and JDBC users should be flagged as "internal"
- [x] https://github.com/gravitee-io/issues/issues/6928, we should be able to send an email
- [x] https://github.com/gravitee-io/issues/issues/6672: we should be able to create an organization user
- [x] https://github.com/gravitee-io/issues/issues/6382: on Register & ForgotPassword, when a PasswordPolicy isn't configured, the submit button should be activated, when a password policy is created it should disable until the password match the rules.
- [x] https://github.com/gravitee-io/issues/issues/5866: when a brute force is enabled, trying to connect an unknown user shouldn't create it if a brute force is detected.
- [ ] https://github.com/gravitee-io/issues/issues/5306 : try to sign in a domain user with the username or the emailAddress
- [x] If two users with different username have the same email address, we should ensure that we request an additional information to specify the username. (need specific configuration)

# Use Cases

1. Sign-in (username/password) flow => Cover by postman end-to-end test

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Connect a user using the flow defined by the application

2. Social sign-in flow

- [x] Create domain
- [x] Create application
- [x] Set-up social IdP
- [x] Connect a user using the social IdP

3. Passwordless sign-in flow

- [x] Create domain
- [x] Create application
- [x] Set-up WebAuthn
- [x] Connect a user using WebAuthn

4. Sign-in (username/password) + MFA flow => Cover by postman end-to-end test

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Set up one MFA factor
- [x] Connect a user with MFA (both Enroll and Challenge step)

5. Social sign-in + MFA flow

- [x] Create domain
- [x] Create application
- [x] Set-up social IdP
- [x] Set up one MFA factor
- [x] Connect a user using the social IdP => should display the MFA Enroll and Challenge pages

6. Passwordless sign-in + MFA flow

- [x] Create domain
- [x] Create application
- [x] Set-up WebAuthn
- [x] Set up one MFA factor
- [x] Connect a user using WebAuthn => should display the MFA Enroll and Challenge pages

7. Sign-in (username/password) with advanced enrich profile flow

- [x] Create domain
- [x] Create application
- [x] Create users
- [x] Create POST-LOGIN flow with both http callout and enrich profile policies
- [x] Connect a user using the flow defined by the application
- [x] Create custom token with enriched profile information
