### ISSUE TITLE
[Async] SSE Entrypoint

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8023]
## :rainbow: Feature

As an Async API Publisher, I want to expose my events to external consumers through a web-friendly streaming protocol such as Server-Sent-Event so that my consumers can consume in realtime a stream of events occurring in my "event-capable" backend from their web/mobile apps.

## :sunrise_over_mountains: Additional information

- [ ] SSE is subscribe only _(Note: Server-Sent Events (SSE) is a server push technology enabling a client to receive automatic updates from a server via an HTTP connection. Its unidirectional nature (only server to client) will allow external consumers to subscribe but not publish (possible with websocket).)_
- [ ] When creating a new API, API owners will have the ability to select SSE as a type of API proxy and will be given the ability to select any of the available SME backend connectors to perform protocol mediation (e.g Expose Kafka events to consumers through an SSE entrypoint).
- [ ] SSE entrypoint should enable text/event-stream content-type on request 
- [ ] Format message depending of the format message from the endpoint 
- [ ] Transform outgoing messages from endpoint format to SSE event.
- [ ] Heartbeat event sent to keep conexion alive
- [ ] Identify event with gravitee message id, if none, generate a new one
- [ ] Use a mock endpoint https://github.com/gravitee-io/issues/issues/8229
- [ ] This is an enterprise edition feature

## Out of scope 

- Handle last event id - to resume the stream from last received messages in case of deconnection 

## :superhero: Acceptance criteria

- [x] Given an Async API configured with a SSE entrypoint then i can establish a connection- #8258 
- [x] Given an Async API configured with a SSE entrypoint then I see events coming from the API When i properly connect to the API via SSE. - #8259
- [ ] Given an Async API configured with a SSE entrypoint then my connexion should keep alive even if there is no events processed - #8261 
- [ ] Given an Async API configured with a SSE entrypoint then i can use compression - #8260
- [ ] Given an Async API configured with a SSE entrypoint then i get automatically reconnected when i loose connection - #8261
- [ ] Given an Async API configured with a SSE entrypoint  then i can keep connection open for 24. hours - #8261
- [ ] Given an Async API with a SSE entrypoint then the queue resume from last sent message when i reconnect after a network failure. - #8262
