### ISSUE TITLE
[Async] Kafka Endpoint

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8024]
## :rainbow: Feature

As an Async API Publisher, I want to connect to a Kafka endpoint in order to subscribe/publish messages 

## :sunrise_over_mountains: Additional information

The Kafka connector needs to be refactored in order to fully leverage the new reactive architecture introduced by Jupiter engine aiming to provide a better decoupling between two important concepts:
- Entrypoints exposed by the Gateway to consumers: SSE, Websocket, Webhook, HTTP Post/Get)
- Endpoints which are backend connectors supported by SME: Kafka, MQTT, AMQP, Kinesis, etc.

The main benefits of decoupling entrypoints from endpoints is that each new SME backend connector will inherently benefit from all supported entrypoints of the platform avoiding the need to reimplement/duplicate same logic in each backend connectors.

- [ ] Persistent connection - configure reconnection settings - #8252
  - `reconnect_backoff_ms`
  - `retries`
  - `retry_backoff_ms`
- [ ] Subscribe to a specific topic #8245
- [ ] Publish to a specific topic #8247
- [ ] Supported format  #8248
  - [ ] JSon
  - [ ] Binary
- [ ] Kafka connector supports establishment of secure connection with Kafka cluster with support of at least ([https://kafka.apache.org/documentation/#security_sasl ](https://kafka.apache.org/documentation/#security_sasl)) - #8250
  - [ ] PLAIN
  - [ ] SCRAM(SHA-256 and SHA-512)
- [ ] Kafka connector supports KSQL (https://docs.confluent.io/platform/current/ksqldb/index.html) - #8251

## 🚫 Out of scope

Note: In order to provide the same functional coverage of what is currently supported by the Kafka connector (based on v3 engine) we will need to also add the following capabilities: 
- [SME] HTTP Post entrypoint - https://github.com/gravitee-io/issues/issues/8036
- [SME] HTTP Get entrypoint - https://github.com/gravitee-io/issues/issues/8037

## :superhero: Acceptance criteria

- [ ] Given an async API with a kafka topic as endpoint Then I can process a message through the gateway When a new one lands in Kafka Topic - #8245
- [ ] Given an async API with a kafka topic as endpoint Then I can view a new message in my topic when i publish it through my API - #8247
- [ ] Given an async API with a kafka topic as endpoint Then I can process a message in binary format - #8248
- [ ] Given an async API with a kafka topic as endpoint Then I can process a message in JSon format -#8248
- [ ] Given an async API with a kafka topic as endpoint then i can establish a secure connection with my kafka topic - #8250
- [ ] Given an async API with a kafka topic as endpoint Then I can use KSQL syntax to sub/pub to it - #8251

**Comment by mouligno** [comment]
to check with - https://github.com/gravitee-io/gravitee-connector-kafka/
