### ISSUE TITLE
[Async] Websocket entrypoint

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8025]
## :rainbow: Feature

As an Async API provider I want to be able to front my Event-Driven backend (Kafka, AMQP, JMS, etc.) with a Websocket API
So that I can provide to my consumers the ability to stream events in real-time to fuel  web/mobile application with real-time data.

## :sunrise_over_mountains: Additional information

- [ ] Establish persistent connection - #8253
- [ ] Receive messages - #8254
- [ ] Send messages - #8255
- [ ] Message format is either text or binary - #8255
- [ ] Support SSL connection - 8256
- [ ] Allow to limit payload size
- [ ] Support CORS configuration

### Out of current scope
- Authentication headers are properly propagated: https://community.gravitee.io/t/apim3-websockets-stomp-security-copying-http-headers-for-ws/696/8 - #8256 - Would be required for proxy APIs WS <-> WS

## :superhero: Acceptance criteria

- [ ] Given an Async API using a WS entrypoint Then I can consume text messages - #8254
- [ ] Given an Async API using a WS entrypoint Then i got an open connection and flow of messages when some are processed by the backend - #8253
- [ ] Given an Async API using a WS entrypoint Then I can publish binary messages that get properly handle by the gateway - #8255
- [ ] Given an Async API using a WS entrypoint Then i can connect to it using SSL - #8256
- [ ] Given an Async API using a WS entrypoint Then i can not send payload over size set in configuration

**Comment by guillaumelamirand** [comment]
@mouligno I have one question regarding the bullet point "Authentication headers are properly propagated". Should they be propagated to who ? With SME we are not proxying websocket socket, so from my point of view, there is nothing to propagated.

**Comment by mouligno** [comment]
@guillaumelamirand good point, i'm updating the ticket accordingly
