### ISSUE TITLE
[management] [forms] override default theme

### ISSUE THREAD

**Issue by tcompiegne** [gravitee-io/issues#8044]
## :rainbow: Feature

**As a** 'security domain owner or application owner'

**I want to** 'override the default theme of my forms'

**So that** 'I can match my brand requirements'

## :sunrise_over_mountains: Additional information

- A color palette will be provided for the best i11y experience. This palette will come with default colors. Currently it will not be possible to a new color
- For every template I can switch between simple (Design) and expert mode (HTML)
- I MUST be able to use my company logo
- By removing my custom theme, the template will be the default one

## :link: Dependencies

Link a story or other related things...

## :camera: Mockups 

<img width="853" alt="Capture d’écran 2022-07-06 à 21 11 24" src="https://user-images.githubusercontent.com/1927438/177625596-b809b0fb-efec-4a5d-a6ca-4d61b0b00440.png">

## :books: Documentation required

Provide link to the issue for documentation update

## :superhero: Acceptance criteria

- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'
- [ ] Given '...' Then '...' When '...'

- [ ] Jest test for acceptance criteria

## :warning: Potential impacts

***Which other features may be impacted by this fix. This could be populated after fix***

***What are the impacted versions?***

:rocket:
