### ISSUE TITLE
[Jupiter] backport grpc (v3 mode)

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8083]
## :rainbow: Feature

As an API Publisher, I want to be able to use gRPC protocole in order to be able to move my existing APIs to Jupiter mode

## :sunrise_over_mountains: Additional information

- Iso functionality as v3 

**Prerequesite:** Learn how gRPC works with V3 gateway
There are already some grpc test performed on the gateway. There are supposed to be run against both v3 and jupiter
https://github.com/gravitee-io/gravitee-api-management/tree/master/gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/src/test/java/io/gravitee/gateway/standalone/grpc

Starting point is to confirm that the above are effectively working

https://www.npmjs.com/package/grpc-server-mock

Switch V3 Gateway to Jupiter and check it is the same behavior (in terms of input vs output).

### out of scope 
- policies
- messaging

## ❓ Pending questions
Should reactivating the following tests be enough to check this is working indeed?
Here are the list of tests explicitly excuded for jupiter: https://github.com/gravitee-io/gravitee-api-management/blob/master/gravitee-apim-gateway/gravitee-apim-gateway-standalone/gravitee-apim-gateway-standalone-container/pom.xml#L464-L471

## Tasks
- [ ] Reactive the excluded tests and check what fails

## :superhero: Acceptance criteria

- [ ] gRPC API feature should work like V3 Gateway
- [ ] Calling a gRPC API in Jupiter should return the same response as calling it directly

**Comment by Sicofonia** [comment]
Refined, ready for sprint.

**Comment by RubenMMSantos** [comment]
pending https://github.com/gravitee-io/issues/issues/8574

**Comment by ytvnr** [comment]
some tests have been added here: https://github.com/gravitee-io/gravitee-api-management/pull/2958
