### ISSUE TITLE
[Jupiter benchmark] Design infrastructure & define initial metrics

### ISSUE THREAD

**Issue by Sicofonia** [gravitee-io/issues#8194]
Define the requirements in term of infrastructure to allow comparing v3 and jupiter performances for september.
This will also contribute to the global vision around performances of the Gravitee platform.
For now, we identified the following:
 - K6
 - Grafana
 - Prometheus
 - Kubernetes cluster (for apim deployment)
 - MongoDB (reuse existing mongodb ?)
 - Elastic (not mandatory for september but could help for diagnostic)
 - Logstash (for tcp reporting, linked to elastic if available)

At first time, we will start to run the K6 scripts locally so we can start to investigation possible performance regressions between v3 and jupiter (if any).
We will soon need a proper environment in order to share the result of our performance tests across the whole team.
For that we need to instantiate a dedicated platform according to the result of the "Define the performance infrastructure requirements" tasks

K6 allows to export a lot of metrics such as request duration, connection duration. We also are able to retrieve infrastructure metrics such as cpu and memory consumption of the gateway.
To propely compare v3 and jupiter performance, we need to identify which indicators we will tracks and make sure that we are collecting them.
For september, we need, at least, be able to compare Jupiter against Jupiter V3 compatibility mode against full V3 without Jupiter

Multiple factors can impact the performance (gateway cpu & mem, use of tcp or file reporter, enable logging, enable https, network, number of instances, ...).
We cannot test all combinaisons so we will choose an ideal situation base on our previous experiences (we know what can have impacts and what has low impact), expectations (we won't do stress tests for now) and we will use the same for our performance tests on v3 and jupiter. That way we will be able to compare results in the same conditions.
Ideally, an deployment architecture diagram can be produced so we can reuse it when explaining the performance results.

### Tasks
- [x] Define the performance infrastructure requirements
- [x] Prepare performance infrastructure
- [x] Identify metrics to collect and compare
- [x] Define APIM deployment architecture

### Acceptance Criteria
- Infrastructure architecture designed with Performance Team and Architecture
- Initial set of metrics agreed with Architecture and Product
