### ISSUE TITLE
[Jupiter benchmark] Develop, tests and troubleshoot a Keyless API scenario with body policies

### ISSUE THREAD

**Issue by Sicofonia** [gravitee-io/issues#8198]
Develop a complete scenario that create a keyless api with a JsonToAxml policy on request and on response and load test it.
This includes running the scenario for the 3 identified cases (v3, jupiter, jupiter with V3 mode) and the analysis of the results. Possibly, in case of performance degradation, diagnostize, fix and test

### Tasks
- [ ] Develop the scenario
- [ ] Test locally comparing v3, jupiter and jupiter with V3 mode
- [ ] If there's noticeable degradation of performance, investigate root cause

### Acceptance Criteria
- No degradation of performance observed when testing a keyless api with body policies scenario
