### ISSUE TITLE
[Jupiter benchmark] Develop, tests and troubleshoot a JWT API test scenario

### ISSUE THREAD

**Issue by Sicofonia** [gravitee-io/issues#8200]
Develop a complete scenario that create a JWT api without any policy or flow to compare performance of V3 vs Jupiter.
This includes running the scenario for the 3 identified cases (v3, jupiter, jupiter with V3 mode) and the analysis of the results. Possibly, in case of performance degradation, diagnostize, fix and test

### Tasks
- [ ] Develop the scenario
- [ ] Test locally comparing v3, jupiter and jupiter with V3 mode
- [ ] If there's noticeable degradation of performance, investigate root cause

### Acceptance Criteria
- No degradation of performance observed when testing a JWT API without any policy or flow scenario.
