### ISSUE TITLE
[Jupiter benchmark] Develop, tests and troubleshoot a EL flow condition scenario

### ISSUE THREAD

**Issue by Sicofonia** [gravitee-io/issues#8202]
Develop a complete scenario that create a keyless API having an empty flow with an EL condition based on the header and load test it.
This includes running the scenario for the 3 identified cases (v3, jupiter, jupiter with V3 mode) and the analysis of the results. Possibly, in case of performance degradation, diagnostize, fix and test

### Tasks
- [ ] Develop the scenario
- [ ] Test locally comparing v3, jupiter and jupiter with V3 mode
- [ ] If there's noticeable degradation of performance, investigate root cause

### Acceptance Criteria
- No degradation of performance observed when testing a keyless api with an EL condition scenario
