### ISSUE TITLE
Make SSE Entrypoint EE

### ISSUE THREAD

**Issue by mouligno** [gravitee-io/issues#8430]
## Description

Move SME SSE Entrypoint to an Enterprise Edition plugin.

## Tasks

- [ ] Create new repository: `gravitee-entrypoint-sse`
- [ ] Extract code from the APIM monorepo with git history and push it in new repo
- [ ] Init all ci stuff (semantic release ext.. )
- [ ] Add license check in java code
- [ ] Release it 
- [ ] Remove it in APIM and use new EE plugin 
- [ ] Add licence in repo + files
- [ ] Add a Readme

**Comment by ThibaudAV** [comment]
https://github.com/gravitee-io/gravitee-entrypoint-sse

**Comment by gaetanmaisse** [comment]
Closing it as it has been moved to Jira https://graviteecommunity.atlassian.net/browse/APIM-117?atlOrigin=eyJpIjoiOGJiZTg5MzRhY2RiNGE2ZTk4MWY5ZTU2OWM1NDQ3MTYiLCJwIjoiaiJ9
